/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.grp5612;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;

import java.io.File;

public class App {

    public static void main(String[] args) throws Exception {
        if (args.length != 1) {
            System.out.println("Usage: java -jar /path/to/app.jar /path/to/file.pdf");
            System.exit(1);
        }

        File file = new File(args[0]);
        if (!file.exists()) {
            System.out.println("No such file: " + args[0]);
        }

        PDDocument doc = PDDocument.load(file);
        PDFTextStripper textStripper = new PDFTextStripper();
        System.out.println(textStripper.getText(doc));
    }
}
